title: My Perception
baseurl: /
permalink: '/posts/:slug:output_ext'
footer:
  social:
    enabled: true
    social_methods:
      - title: Twitter
        icon: fab fa-twitter
        link: '#'
      - title: Facebook
        icon: fab fa-facebook-f
        link: '#'
      - title: Comment
        icon: fas fa-comment
        link: '#'
      - title: Bookmark
        icon: fas fa-bookmark
        link: '#'
  bottom:
    blurb:
      enabled: true
      img: images/person.svg
      description:
        heading: Anna Goldfarb
        subheading: writer & Journalist
        content: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
    copyright:
      enabled: true
      text: '&copy; Perception. All rights reserved. Lorem ipsum dolor sit amet.'
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
