---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: null
sections:
  - type: document
    label: Config
    path: _config.yml
    templates:
      - config
  - type: document
    label: Social Links
    path: _data/social.json
    templates:
      - social
  - type: document
    label: Author
    path: _data/author.json
    templates:
      - author
  - type: document
    label: Home
    path: index.md
    templates:
      - home
  - type: directory
    path: ''
    match: '**/*.md'
    exclude: '{_posts/**,README.md,LICENSE.md,index.md,contact.md}'
    label: Pages
    create: all
    templates:
      - page
  - type: jekyll-posts
    label: Posts
    create: all
    templates:
      - post
  - type: directory
    path: ''
    match: '**/*.md'
    exclude: '{README.md,LICENSE.md,index.md,contact.md}'
    label: Basic Pages
    create: all
    templates:
      - basic
  - type: document
    label: Contact Page
    path: contact.md
    templates:
      - contact
upload_dir: images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
